#!/bin/bash
#awk 'BEGIN{split("",a); a[1]="2L";a[2]="2R";a[3]="3L";a[4]="3R";a[5]="4";a[6]="X";a[7]="Y";}
#        {b="";
#                for (i=1;i<=7;i++)
#                        {
#                        if($2 !~ a[i]) b=sprintf("%s--not-chr %s ",b,a[i])
#                        };
#                print "vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf",b,"--chr",$2,"--from-bp",$5,"--to-bp",$6,"--out",$1,"--recode";}' dmel_targets > batch
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 4 --not-chr X --not-chr Y  --chr 3R --from-bp 11924938 --to-bp 11930239 --out Akt1 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 3L --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 2R --from-bp 6156521 --to-bp 6194529 --out CAP --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 2L --from-bp 10242512 --to-bp 10247078 --out chico --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr Y  --chr X --from-bp 3267192 --to-bp 3285730 --out dm --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 3L --from-bp 9392718 --to-bp 9395560 --out eIF-4E --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 3L --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 2R --from-bp 11453776 --to-bp 11456909 --out Flo-1 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr Y  --chr X --from-bp 14733407 --to-bp 14827616 --out Flo-2 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 4 --not-chr X --not-chr Y  --chr 3R --from-bp 9882667 --to-bp 9913700 --out foxo --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 3L --from-bp 20122281 --to-bp 20132110 --out gig --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 3L --from-bp 9791534 --to-bp 9791998 --out Ilp1 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 3L --from-bp 9792798 --to-bp 9793540 --out Ilp2 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 3L --from-bp 9794398 --to-bp 9795220 --out Ilp3 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 3L --from-bp 9796499 --to-bp 9797363 --out Ilp4 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 3L --from-bp 9816449 --to-bp 9816997 --out Ilp5 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr Y  --chr X --from-bp 2225526 --to-bp 2228691 --out Ilp6 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr Y  --chr X --from-bp 3561654 --to-bp 3562878 --out Ilp7 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 4 --not-chr X --not-chr Y  --chr 3R --from-bp 17395970 --to-bp 17445043 --out InR --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 4 --not-chr X --not-chr Y  --chr 3R --from-bp 9502271 --to-bp 9505152 --out lkb1 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 3L --from-bp 129450 --to-bp 145895 --out Pdk1 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 2L --from-bp 297880 --to-bp 305233 --out Pi3K21B --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 4 --not-chr X --not-chr Y  --chr 3R --from-bp 16454694 --to-bp 16460454 --out Pi3K92E --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 2L --from-bp 10256319 --to-bp 10261049 --out Pten --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 4 --not-chr X --not-chr Y  --chr 3R --from-bp 4808454 --to-bp 4810029 --out RagA-B --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 3L --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 2R --from-bp 4049184 --to-bp 4051005 --out RagC-D --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr Y  --chr X --from-bp 5976692 --to-bp 5984234 --out raptor --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 4 --not-chr X --not-chr Y  --chr 3R --from-bp 1394643 --to-bp 1396213 --out Rheb --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr Y  --chr X --from-bp 19146144 --to-bp 19155259 --out rictor --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr Y  --chr X --from-bp 7793653 --to-bp 7795362 --out RpS6 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 3L --from-bp 5790649 --to-bp 5804031 --out S6k --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr Y  --chr X --from-bp 2527985 --to-bp 2571879 --out sgg --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 4 --not-chr X --not-chr Y  --chr 3R --from-bp 25884033 --to-bp 25947520 --out sima --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 3L --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 2R --from-bp 10299330 --to-bp 10301356 --out Sin1 --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr Y  --chr X --from-bp 1269569 --to-bp 1272929 --out SNF1A --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 4 --not-chr X --not-chr Y  --chr 3R --from-bp 16966461 --to-bp 17039991 --out SNF4Agamma --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 2L --from-bp 21740041 --to-bp 21757466 --out step --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 2L --from-bp 3478434 --to-bp 3479612 --out Thor --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2R --not-chr 3L --not-chr 3R --not-chr 4 --not-chr X --not-chr Y  --chr 2L --from-bp 13004480 --to-bp 13013197 --out Tor --recode
vcftools --vcf /net/home/carlesba/db/DGRP/f.vcf --not-chr 2L --not-chr 2R --not-chr 3L --not-chr 4 --not-chr X --not-chr Y  --chr 3R --from-bp 19956029 --to-bp 19960376 --out Tsc1 --recode
