#!/bin/bash
AN=~/code/tests1
TAR=~/project/dmel_targets
echo "#!/bin/bash" > $AN
echo "#Tajima's D tests results:" > ~/project/TajimaD
echo "R --slave -f MK.R" >> $AN
echo "R --slave -f SEMK.R" >> $AN
awk '{print "R --slave -f ~/code/TajimaD.R --args",$1,">> ~/project/TajimaD"}' $TAR >> $AN

chmod +x $AN
