#!/bin/bash
#awk program -- chr = $2, bp = $3, $4, name = $1
#First print a command to separate all of the chromosomes:
echo "#Vcftools code to separate the chromosomes of interest:" > batchbychr
awk '{print $2}' ~/project/dmel_targets | sort | uniq | awk '{print"/net/home/carlesba/bin/vcftools_0.1.11/bin/vcftools --vcf f.vcf --chr",$1,"--recode --out",$1}' >> batchbychr

#An awk program that writes an awk program:
echo "#Awk program to pick out SNPs of interest (from the dmel_targets genes):" >> batchbychr
awk '{a=sprintf("%s_recode.vcf",$1);b=sprintf("%s.recode.vcf",$2); print "awk \x27 $2 >=",$5,"&& $3 <=",$6,"\x27",b,">",a}' ~/project/dmel_targets >> batchbychr

#Enable execution
chmod +x batchbychr

#Qsub command:
#qsub -clear -cwd -N batch_chr -b y ./batchbychr

