#!/bin/bash
# make sure the target inputs are sorted!
# PUTS TOGETHER THE FBgn# from 5.33 (to match it against the Simv2) and the data from the current update, 5.51
if [ "$1" == "" ]
then
    ARG=~/project/targets
else
    ARG=$1
fi

cat ~/db/Annotation/dmel-all-r5.51.gff | awk '$2~/FlyBase/ && $3~/gene/{gsub("ID=",";",$0); gsub("Name=","n;",$0);print}' | awk 'BEGIN{FS=";"; OFS="\t"}{print $4,$1,$2}' | sort +0 -1 > a
cat ~/db/Annotation/dmel-all-r5.33.gff | awk '$2~/FlyBase/ && $3~/gene/{gsub("ID=",";",$0); gsub("Name=","n;",$0);print}' | awk 'BEGIN{FS=";"; OFS="\t"}{print $4,$2}' | sort +0 -1 > c
awk '{print $1}' $ARG | sort +0 -1 > b
join b a | join - c > ~/project/dmel_targets
rm a b c
