#!/bin/bash
#Takes out the chromosomes from the dsim chromosome file, 1.4 release, leaving only the chromosomes numbers ($1) and the sequence ($2)
awk 'BEGIN{RS=">";ORS="\n>"}$0 ~ /loc=[234XYLR]*:/' dsim-all-chromosome-r1.4.fasta | awk 'BEGIN{RS="\n>";}{gsub("\n","");gsub(" type.*sim;","\t");print}' > chrsim

awk 'NR==1{print $2}' chrsim > chr4sim
awk 'NR==2{print $2}' chrsim > chrXsim
awk 'NR==3{print $2}' chrsim > chr2Lsim
awk 'NR==4{print $2}' chrsim > chr3Rsim 
awk 'NR==5{print $2}' chrsim > chr2Lsim
awk 'NR==6{print $2}' chrsim > chr2Rsim     
