#!/bin/bash
sed -n '4315744,4315852p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Akt1_full.vcf
sed -n '1593530,1595648p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/CAP_full.vcf
sed -n '706424,706634p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/chico_full.vcf
sed -n '5357245,5358087p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/dm_full.vcf
sed -n '3095885,3095981p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/eIF-4E_full.vcf
sed -n '5859237,5864971p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Flo-2_full.vcf
sed -n '4208137,4210376p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/foxo_full.vcf
sed -n '3746445,3746600p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/gig_full.vcf
sed -n '3120025,3120052p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Ilp1_full.vcf
sed -n '3120087,3120115p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Ilp2_full.vcf
sed -n '3120229,3120277p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Ilp3_full.vcf
sed -n '3120364,3120397p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Ilp4_full.vcf
sed -n '3122118,3122131p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Ilp5_full.vcf
sed -n '5310526,5310627p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Ilp6_full.vcf
sed -n '5370821,5370859p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Ilp7_full.vcf
sed -n '4632724,4635054p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/InR_full.vcf
sed -n '4184069,4184153p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/lkb1_full.vcf
sed -n '6091,6299p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Pi3K21B_full.vcf
sed -n '4580838,4580988p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Pi3K92E_full.vcf
sed -n '707222,707478p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Pten_full.vcf
sed -n '5478474,5478627p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/raptor_full.vcf
sed -n '3893953,3893969p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Rheb_full.vcf
sed -n '6032133,6032272p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/rictor_full.vcf
sed -n '5550645,5550675p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/RpS6_full.vcf
sed -n '2863446,2864268p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/S6k_full.vcf
sed -n '5321690,5323624p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/sgg_full.vcf
sed -n '5139112,5143547p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/sima_full.vcf
sed -n '1843034,1843100p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Sin1_full.vcf
sed -n '5289936,5289994p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/SNF1A_full.vcf
sed -n '4606873,4612089p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/SNF4Agamma_full.vcf
sed -n '1342556,1343212p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/step_full.vcf
sed -n '208678,208744p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Thor_full.vcf
sed -n '892756,892947p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Tor_full.vcf
sed -n '4792940,4793058p;'  ~/db/DGRP/f.vcf | awk '{gsub(/[A-Z]*:[0-9:A-Z]*:[A-Z]*/,"\t",$0); gsub(/[0-9]*\//,"",$0); print}' > ~/db/DGRP/fullgenes/Tsc1_full.vcf

#Setting all nonreads to 0, and NO threshold, for Tajima's D:
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Akt1_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Akt1_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/CAP_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/CAP_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/chico_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/chico_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Cyp6a16Psi_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Cyp6a16Psi_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Cyp6t2Psi_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Cyp6t2Psi_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Cyp9f3Psi_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Cyp9f3Psi_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/dm_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/dm_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/eIF-4E_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/eIF-4E_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Flo-2_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Flo-2_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/foxo_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/foxo_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/gig_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/gig_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Ilp1_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Ilp1_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Ilp2_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Ilp2_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Ilp3_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Ilp3_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Ilp4_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Ilp4_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Ilp5_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Ilp5_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Ilp6_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Ilp6_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Ilp7_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Ilp7_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/InR_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/InR_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/lkb1_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/lkb1_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Pi3K21B_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Pi3K21B_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Pi3K92E_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Pi3K92E_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Pten_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Pten_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/raptor_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/raptor_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Rheb_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Rheb_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/rictor_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/rictor_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/RpS6_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/RpS6_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/S6k_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/S6k_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/sgg_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/sgg_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/sima_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/sima_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Sin1_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Sin1_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/SNF1A_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/SNF1A_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/SNF4Agamma_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/SNF4Agamma_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/step_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/step_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Thor_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Thor_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Tor_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Tor_SNP
awk ' $0 ~/SY/{print "0",$0} $0 ~/NS/{print "1",$0}'  ~/db/DGRP/fullgenes/Tsc1_full.vcf | tr . 0 > ~/db/DGRP/fullgenes/Tsc1_SNP
With a threshold of 20 = read quality, we pick out the reads and print allele count, avg. quality, sequences used, not used, and total for divergence tests
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Akt1_full.vcf > ~/db/DGRP/fullgenes/Akt1_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/CAP_full.vcf > ~/db/DGRP/fullgenes/CAP_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/chico_full.vcf > ~/db/DGRP/fullgenes/chico_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Cyp6a16Psi_full.vcf > ~/db/DGRP/fullgenes/Cyp6a16Psi_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Cyp6t2Psi_full.vcf > ~/db/DGRP/fullgenes/Cyp6t2Psi_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Cyp9f3Psi_full.vcf > ~/db/DGRP/fullgenes/Cyp9f3Psi_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/dm_full.vcf > ~/db/DGRP/fullgenes/dm_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/eIF-4E_full.vcf > ~/db/DGRP/fullgenes/eIF-4E_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Flo-2_full.vcf > ~/db/DGRP/fullgenes/Flo-2_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/foxo_full.vcf > ~/db/DGRP/fullgenes/foxo_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/gig_full.vcf > ~/db/DGRP/fullgenes/gig_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Ilp1_full.vcf > ~/db/DGRP/fullgenes/Ilp1_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Ilp2_full.vcf > ~/db/DGRP/fullgenes/Ilp2_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Ilp3_full.vcf > ~/db/DGRP/fullgenes/Ilp3_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Ilp4_full.vcf > ~/db/DGRP/fullgenes/Ilp4_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Ilp5_full.vcf > ~/db/DGRP/fullgenes/Ilp5_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Ilp6_full.vcf > ~/db/DGRP/fullgenes/Ilp6_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Ilp7_full.vcf > ~/db/DGRP/fullgenes/Ilp7_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/InR_full.vcf > ~/db/DGRP/fullgenes/InR_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/lkb1_full.vcf > ~/db/DGRP/fullgenes/lkb1_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Pi3K21B_full.vcf > ~/db/DGRP/fullgenes/Pi3K21B_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Pi3K92E_full.vcf > ~/db/DGRP/fullgenes/Pi3K92E_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Pten_full.vcf > ~/db/DGRP/fullgenes/Pten_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/raptor_full.vcf > ~/db/DGRP/fullgenes/raptor_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Rheb_full.vcf > ~/db/DGRP/fullgenes/Rheb_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/rictor_full.vcf > ~/db/DGRP/fullgenes/rictor_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/RpS6_full.vcf > ~/db/DGRP/fullgenes/RpS6_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/S6k_full.vcf > ~/db/DGRP/fullgenes/S6k_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/sgg_full.vcf > ~/db/DGRP/fullgenes/sgg_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/sima_full.vcf > ~/db/DGRP/fullgenes/sima_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Sin1_full.vcf > ~/db/DGRP/fullgenes/Sin1_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/SNF1A_full.vcf > ~/db/DGRP/fullgenes/SNF1A_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/SNF4Agamma_full.vcf > ~/db/DGRP/fullgenes/SNF4Agamma_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/step_full.vcf > ~/db/DGRP/fullgenes/step_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Thor_full.vcf > ~/db/DGRP/fullgenes/Thor_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Tor_full.vcf > ~/db/DGRP/fullgenes/Tor_divSNP
awk '$0 ~/SY/ || $0 ~/NS/{qual= 0;count=0;no = 0;allele=0;for(i=9;i <=NF; i= i+2){a = i+1; if($i ~ /\./ || $a < 20){no = no +1}; if(($i == 1 || $i == 0) && $a >= 20){count=count+1;qual = qual + $a}; if($i == 1 && $a >= 20){allele = allele + $i;}}; print allele,qual/count,count,no,no+count,$8;}'  ~/db/DGRP/fullgenes/Tsc1_full.vcf > ~/db/DGRP/fullgenes/Tsc1_divSNP
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Akt1",sy,ns }' ~/db/DGRP/fullgenes/Akt1_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "CAP",sy,ns }' ~/db/DGRP/fullgenes/CAP_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "chico",sy,ns }' ~/db/DGRP/fullgenes/chico_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Cyp6a16Psi",sy,ns }' ~/db/DGRP/fullgenes/Cyp6a16Psi_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Cyp6t2Psi",sy,ns }' ~/db/DGRP/fullgenes/Cyp6t2Psi_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Cyp9f3Psi",sy,ns }' ~/db/DGRP/fullgenes/Cyp9f3Psi_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "dm",sy,ns }' ~/db/DGRP/fullgenes/dm_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "eIF-4E",sy,ns }' ~/db/DGRP/fullgenes/eIF-4E_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Flo-2",sy,ns }' ~/db/DGRP/fullgenes/Flo-2_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "foxo",sy,ns }' ~/db/DGRP/fullgenes/foxo_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "gig",sy,ns }' ~/db/DGRP/fullgenes/gig_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Ilp1",sy,ns }' ~/db/DGRP/fullgenes/Ilp1_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Ilp2",sy,ns }' ~/db/DGRP/fullgenes/Ilp2_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Ilp3",sy,ns }' ~/db/DGRP/fullgenes/Ilp3_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Ilp4",sy,ns }' ~/db/DGRP/fullgenes/Ilp4_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Ilp5",sy,ns }' ~/db/DGRP/fullgenes/Ilp5_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Ilp6",sy,ns }' ~/db/DGRP/fullgenes/Ilp6_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Ilp7",sy,ns }' ~/db/DGRP/fullgenes/Ilp7_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "InR",sy,ns }' ~/db/DGRP/fullgenes/InR_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "lkb1",sy,ns }' ~/db/DGRP/fullgenes/lkb1_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Pi3K21B",sy,ns }' ~/db/DGRP/fullgenes/Pi3K21B_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Pi3K92E",sy,ns }' ~/db/DGRP/fullgenes/Pi3K92E_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Pten",sy,ns }' ~/db/DGRP/fullgenes/Pten_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "raptor",sy,ns }' ~/db/DGRP/fullgenes/raptor_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Rheb",sy,ns }' ~/db/DGRP/fullgenes/Rheb_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "rictor",sy,ns }' ~/db/DGRP/fullgenes/rictor_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "RpS6",sy,ns }' ~/db/DGRP/fullgenes/RpS6_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "S6k",sy,ns }' ~/db/DGRP/fullgenes/S6k_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "sgg",sy,ns }' ~/db/DGRP/fullgenes/sgg_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "sima",sy,ns }' ~/db/DGRP/fullgenes/sima_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Sin1",sy,ns }' ~/db/DGRP/fullgenes/Sin1_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "SNF1A",sy,ns }' ~/db/DGRP/fullgenes/SNF1A_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "SNF4Agamma",sy,ns }' ~/db/DGRP/fullgenes/SNF4Agamma_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "step",sy,ns }' ~/db/DGRP/fullgenes/step_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Thor",sy,ns }' ~/db/DGRP/fullgenes/Thor_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Tor",sy,ns }' ~/db/DGRP/fullgenes/Tor_divSNP >> ~/project/divergence/DGRPdiv
awk ' BEGIN{sy=0;ns=0;} $0 ~ /SY/{sy=sy+1}$0 ~/NS/{ns=ns+1}END{print "Tsc1",sy,ns }' ~/db/DGRP/fullgenes/Tsc1_divSNP >> ~/project/divergence/DGRPdiv
awk '{print $1,$2,$3}' ~/project/divergence/allsimdiv | join - ~/project/divergence/DGRPdiv > ~/project/divergence/fulldiv
