#!/bin/bash
PREFIX=/net/home/carlesba
TAR=$PREFIX/project/dmel_targets
code=$PREFIX/code/TajimaD.R
out=$PREFIX/project/TajimaD

DGRPDIV=$PREFIX/project/divergence/DGRPdiv 
SIMDIV=$PREFIX/project/divergence/cd.sim.div
YAKDIV=$PREFIX/project/divergence/cd.yak.div
FULLDIV=$PREFIX/project/divergence/simfulldiv 
FULLDIV2=$PREFIX/project/divergence/yakfulldiv 

awk '{print $1,$2,$3}' $SIMDIV | sort +0 -1 | join - $DGRPDIV > $FULLDIV 
awk '{print $1,$2,$3}' $YAKDIV | sort +0 -1 | join - $DGRPDIV > $FULLDIV2

# New file:
echo "" > $out

# Output Tajima's D results
while read -r p
do
    eval $( echo $p | awk '{printf("GENE=%s",$1)}' )
    R --slave -f $code --args $GENE >> $out
done < $TAR

# McDonald -Kreitman test with Fishers and with Alpha value:
R --slave -f MK.R
R --slave -f SEMK.R
