#!/bin/bash
# make sure the target inputs are sorted!
# PUTS TOGETHER THE FBgn# from 5.33 (to match it against the Simv2) and the data from the current update, 5.51
PREFIX=/net/home/carlesba

if [ "$1" == "" ]
then
    ARG=$PREFIX/project/targets
else
    ARG=$1
fi

cat ~/db/Annotation/dmel-all-r5.51.gff | awk '$2~/FlyBase/ && $3~/gene/{gsub("ID=",";",$0); gsub("Name=","n;",$0);print}' | awk 'BEGIN{FS=";"; OFS="\t"}{print $4,$1,$2}' | sort +0 -1 > a
cat ~/db/Annotation/dmel-all-r5.33.gff | awk '$2~/FlyBase/ && $3~/gene/{gsub("ID=",";",$0); gsub("Name=","n;",$0);print}' | awk 'BEGIN{FS=";"; OFS="\t"}{print $4,$2}' | sort +0 -1 > c
awk '{print $1}' $ARG | sort +0 -1 > b
join b a | join - c | awk '{name=$1; gsub(/\(/,"_",$1); gsub(/\)/,"_",$1); gsub(/\x27/,"_",$1); gsub(/:/,"_",$1); print $0,($5-$4+1),name}' > $PREFIX/project/dmel_targets

# Split for fast processing!
mkdir -p $PREFIX/project/genes/
awk -v prefix=$PREFIX '{len=((NR - NR % 100)/100 + 1); print > prefix "/project/genes/" int(len) "dmel_targets"}' $PREFIX/project/dmel_targets

#Create RANDOM SERIES OF GENES to compare against. (Are the genes we are seeing significant??)
eval $( awk 'END{printf("NRGENES=%s",NR)}' a )
if [[ ! -e $PREFIX/project/random_targets ]] 
then {
    Rscript -e 'args <- commandArgs(TRUE);write(round(runif(1500,1,as.numeric(args[1]))),paste(args[2],"/project/rg",sep=""))' $NRGENES $PREFIX
    awk '{gsub(" ","\n"); print $0}' $PREFIX/project/rg | sort -u > $PREFIX/project/randomnum
    rm $PREFIX/project/rg

    rm $PREFIX/project/randomgenes
while read -r p 
do 
    eval $( echo $p | awk -v pref=$PREFIX '{printf("sed -n \"%sp\" a >> %s/project/randomgenes",$1,pref)}' )
done < $PREFIX/project/randomnum

#once the randomgenes are done:
    sort +0 -1 $PREFIX/project/randomgenes | join - c | awk '{name=$1; gsub(/\(/,"_",$1); gsub(/\)/,"_",$1); gsub(/\x27/,"_",$1); gsub(/:/,"_",$1); print $0,($5-$4+1),name}' > $PREFIX/project/random_targets
    mkdir -p $PREFIX/project/random
    awk -v prefix=$PREFIX '{len=((NR - NR % 100)/100 + 1); print > prefix "/project/random/" int(len) "random_targets"}' $PREFIX/project/random_targets

rm $PREFIX/project/randomnum
} fi

rm a b c
