#!/usr/bin/python
# Run in python
for i in range(1,14):
    string = "qsub -clear -cwd -N DGRP" + str(i) + " -b y ~/code/parseDGRP ~/project/genes/" +str(i)+"dmel_targets"
    print(string) 

for i in range(1,14):
    string = "qsub -clear -cwd -N rDGRP" + str(i) + " -b y ~/code/parseDGRP ~/project/random/" +str(i)+"random_targets"
    print(string) 

for i in range(1,14):
    string = "qsub -clear -cwd -N remaps" + str(i) + " -b y ~/code/remapYak ~/project/genes/" +str(i)+"dmel_targets"
    print(string) 

for i in range(1,14):
    string = "qsub -clear -cwd -N rdremaps" + str(i) + " -b y ~/code/remapYak ~/project/random/" +str(i)+"random_targets"
    print(string) 

for i in range(1,14):
    string = "qsub -clear -cwd -N sim" + str(i) + " -b y ~/code/parseSIMV2 ~/project/genes/" +str(i)+"dmel_targets"
    print(string) 

for i in range(1,14):
    string = "qsub -clear -cwd -N rdsim" + str(i) + " -b y ~/code/parseSIMV2 ~/project/random/" +str(i)+"random_targets"
    print(string) 


#AFTER this, we run: 
~/code/parseDGRP 
~/code/parseDGRP CONTROL
~/code/parseSIMV2
~/code/parseSIMV2 CONTROL
~/code/remapYak 
~/code/remapYak CONTROL
